# Docker image to use
image: adoptopenjdk/openjdk11

# Define stages
#   Stages group various steps into one block,
#   if any step fails, the entire stage fails
stages:
  - build

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
