stages:
  - build
  - test
  - sonarqube
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
test:
    stage: test
    dependencies:
      - build
    script:
      - mvn $MAVEN_CLI_OPTS test
sonarqube:
  stage: sonarqube
  dependencies:
    - test
  script:
    - mvn verify sonar:sonar "-Desonar.qualitygate=true"
after_script:
    - echo "End CI"