stages:
  - build
  - test
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
test:
    stage: test
    dependencies:
      - build
    script:
      - mvn $MAVEN_CLI_OPTS test
      
after_script:
    - echo "End CI"
