--- 
after_script: 
  - "echo \"End CI\""
artifacts: 
  reports: 
    junit: 
      - target/surefire-reports/TEST-*.xml
      - target/failsafe-reports/TEST-*.xml
  when: always
build: 
  script: 
    - "mvn $MAVEN_CLI_OPTS compile"
  stage: build
stages: 
  - build
  - test
test: 
  dependencies: 
    - build
  script: 
    - "mvn $MAVEN_CLI_OPTS test"
  stage: test