--- 
networks: 
  food-app-mysql: ~
services:
  food-delivery-app:
    depends_on: 
      - mysql
    image: food-delivery-app
    networks: 
      - food-app-mysql
    ports:
      - "9999:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3307/food_delivery

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    ports:
      - 3307:3306

    image: "mysql:8"
    networks: 
      - food-app-mysql
version: "3"